"use client";

import { FormEvent, useEffect, useState } from "react";
import { authenticatedFetch } from "../../../lib/auth-client";

type Props={exercise:{id:string;title:string;instructions:string;exercise_type:string;max_score:number}};
type VerifyResult={passed:boolean;score:number;percentage:number;feedback:string;hint:string|null;missingFields:string[];saved?:boolean;lessonId?:string;learningComplete?:boolean;revealedAnswer?:string|null;explanation?:string|null;assistanceLevel?:number};
type CoachResult={reply?:string;error?:string};type UiField={key:string;label:string;type:"text"|"number"};type UiMeta={mode:"form"|"ordered-list"|"single"|"multiple-choice";fields:UiField[];items?:number;options?:string[]};
export default function ExerciseCard({exercise}:Props){
 const[ui,setUi]=useState<UiMeta|null>(null);const[values,setValues]=useState<Record<string,string>>({});const[ordered,setOrdered]=useState<string[]>([]);const[single,setSingle]=useState("");const[result,setResult]=useState<VerifyResult|null>(null);const[loading,setLoading]=useState(false);const[hintLevel,setHintLevel]=useState(0);const[hints,setHints]=useState<string[]>([]);const[hintLoading,setHintLoading]=useState(false);
 useEffect(()=>{fetch(`/api/exercise-ui?exerciseId=${exercise.id}`).then(r=>r.json()).then((data:UiMeta)=>{setUi(data);setResult(null);setHintLevel(0);setHints([]);setSingle("");setValues({});if(data.mode==="ordered-list")setOrdered(Array.from({length:data.items??4},()=>""));});},[exercise.id]);
 function answerPayload():unknown{if(!ui)return{};if(ui.mode==="ordered-list")return ordered.map(v=>v.trim()).filter(Boolean);if(ui.mode==="single"||ui.mode==="multiple-choice")return single.trim();return Object.fromEntries(ui.fields.map(field=>[field.key,field.type==="number"?Number(values[field.key]||0):(values[field.key]??"").trim()]));}
 function completeIfNeeded(data:VerifyResult){setResult(data);if(data.learningComplete&&data.lessonId)window.dispatchEvent(new CustomEvent("erp-lesson-completed",{detail:{lessonId:data.lessonId}}));}
 async function submitAnswer(assistanceLevel=hintLevel){setLoading(true);try{const response=await authenticatedFetch("/api/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({exerciseId:exercise.id,answer:answerPayload(),assistanceLevel})});if(!response)return;completeIfNeeded(await response.json() as VerifyResult);}finally{setLoading(false);}}
 async function verify(event:FormEvent){event.preventDefault();await submitAnswer();}
 async function getHint(){if(hintLevel>=3||hintLoading)return;const next=hintLevel+1;setHintLoading(true);try{const response=await authenticatedFetch("/api/coach",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:"lesson",exerciseId:exercise.id,hintLevel:next,prompt:`Give progressive hint ${next} of 3. Hint 1 should only point toward the concept. Hint 2 should connect the business process. Hint 3 may be a strong clue but must not state the final answer. Keep it short and beginner-friendly.`})});if(!response)return;const data=await response.json() as CoachResult;setHintLevel(next);setHints(old=>[...old,data.reply??data.error??"Coach is unavailable right now."]);}finally{setHintLoading(false);}}
 const hasInput=ui?.mode==="form"?ui.fields.some(f=>(values[f.key]??"").trim()):ui?.mode==="ordered-list"?ordered.some(Boolean):single.trim().length>0;
 return <section className="lessonExercise"><div className="lessonExerciseHeader"><span className="eyebrow">Practice</span><span className="scorePill">{exercise.max_score} XP</span></div><h3>{exercise.title}</h3><p>{exercise.instructions}</p><form onSubmit={verify} className="beginnerQuestion">
 {!ui&&<p className="muted">Loading question…</p>}
 {ui?.mode==="multiple-choice"&&<fieldset className="choiceGroup"><legend>Choose the best answer</legend>{ui.options?.map(option=><label key={option} className={single===option?"choiceCard selected":"choiceCard"}><input type="radio" name={`exercise-${exercise.id}`} value={option} checked={single===option} onChange={e=>setSingle(e.target.value)}/><span>{option}</span></label>)}</fieldset>}
 {ui?.mode==="single"&&<label className="erpSingle"><span>Type a short answer</span><input value={single} onChange={e=>setSingle(e.target.value)} placeholder="One word or short answer" autoComplete="off"/></label>}
 {ui?.mode==="ordered-list"&&<div className="erpFieldGrid">{ordered.map((value,index)=><label key={index}><span>Step {index+1}</span><input value={value} onChange={e=>setOrdered(items=>items.map((x,i)=>i===index?e.target.value:x))}/></label>)}</div>}
 {ui?.mode==="form"&&<div className="erpFieldGrid">{ui.fields.map(field=><label key={field.key}><span>{field.label}</span><input type={field.type} value={values[field.key]??""} onChange={e=>setValues(v=>({...v,[field.key]:e.target.value}))}/></label>)}</div>}
 <div className="exerciseActions"><button className="primaryButton" disabled={loading||!hasInput}>{loading?"Checking…":"Check answer"}</button><button type="button" className="secondaryButton" disabled={hintLevel>=3||hintLoading} onClick={()=>void getHint()}>{hintLoading?"Getting hint…":hintLevel===0?"Hint 1 of 3":hintLevel<3?`Hint ${hintLevel+1} of 3`:"All 3 hints used"}</button></div></form>
 {hints.length>0&&<div className="hintStack" aria-live="polite">{hints.map((hint,index)=><div className="coachNote" key={index}><p><strong>Hint {index+1}:</strong> {hint}</p></div>)}</div>}
 {hintLevel>=3&&!result?.learningComplete&&!result?.passed&&<div className="answerRevealAction"><p>You have used all three hints. Learning should not stop here.</p><button type="button" className="secondaryButton" disabled={loading} onClick={()=>void submitAnswer(3)}>Show answer & explanation</button></div>}
 {result&&<div className={`verifyResult ${result.passed?"pass":"retry"}`} aria-live="polite"><strong>{result.passed?"Correct — well done!":result.revealedAnswer?"Learn the answer, then continue":"Not quite — keep learning"}</strong><p>{result.feedback}</p>{!result.passed&&!result.revealedAnswer&&hintLevel<3&&<p className="muted">Try again, or use the next hint. A mistake here will not block your learning.</p>}{result.revealedAnswer&&<div className="revealedLearning"><span className="microLabel">Correct answer</span><strong className="revealedAnswer">{result.revealedAnswer}</strong>{result.explanation&&<p><strong>Why:</strong> {result.explanation}</p>}<p className="muted">This lesson is complete for learning purposes. ERP Edu will revisit this concept later so you can prove it independently.</p></div>}{result.learningComplete&&result.saved&&<p><strong>Continue:</strong> Your progress is saved and the next lesson is unlocked.</p>}</div>}
 </section>;
}
