import { test, expect } from '@playwright/test';

test.describe('Customer master and AR clearing',()=>{
  test('validates customer master, clears receivable, blocks duplicate payment, and reopens on reversal',async({page},testInfo)=>{
    test.skip(testInfo.project.name!=='chromium','Financial lifecycle certification runs once on desktop.');test.setTimeout(120000);
    const email=process.env.E2E_LEARNER_EMAIL,password=process.env.E2E_LEARNER_PASSWORD;test.skip(!email||!password,'Requires CI learner.');
    await page.goto('/auth');await page.getByLabel('Email').fill(email!);await page.getByLabel('Password').fill(password!);await page.getByRole('button',{name:'Sign in'}).last().click();await expect(page).toHaveURL(/\/dashboard$/,{timeout:20000});
    const result=await page.evaluate(async()=>{
      const token=JSON.parse(localStorage.getItem('erp-edu-session')||'{}').access_token;if(!token)throw new Error('Missing token');const headers={'Content-Type':'application/json',Authorization:`Bearer ${token}`};
      async function post(url:string,action:string,data:Record<string,unknown>,expected=200){const r=await fetch(url,{method:'POST',headers,body:JSON.stringify({action,data})});const b=await r.json();if(r.status!==expected)throw new Error(`${action} ${r.status}: ${JSON.stringify(b)}`);return b;}
      const state=await fetch('/api/erp-runtime',{headers:{Authorization:headers.Authorization}}).then(r=>r.json());const m=state.masterData??[];const mat=m.find((x:Record<string,unknown>)=>x.entity_type==='material')?.code,plant=m.find((x:Record<string,unknown>)=>x.entity_type==='plant')?.code,vendor=m.find((x:Record<string,unknown>)=>x.entity_type==='vendor')?.code,porg=m.find((x:Record<string,unknown>)=>x.entity_type==='purchasing_organization')?.code,storage=m.find((x:Record<string,unknown>)=>x.entity_type==='storage_location')?.code;if(!mat||!plant||!vendor||!porg||!storage)throw new Error('Missing masters');const today=new Date().toISOString().slice(0,10),customer=`CUST-${Date.now().toString().slice(-6)}`;
      const invalidCustomer=await post('/api/sales-flow','create_sales_order',{customer:'CUST-MISSING',plant,material:mat,quantity:1,unit_price:100},400);
      const created=await post('/api/customer-master','create',{customer_code:customer,name:'AR Clearing Customer',currency:'INR',payment_terms:'NET30',credit_limit:10000});
      const duplicateCustomer=await post('/api/customer-master','create',{customer_code:customer,name:'Duplicate'},409);
      const pr=await post('/api/procurement-flow/multiline','create_pr',{plant,items:[{line_number:10,material:mat,quantity:3}]});const po=await post('/api/procurement-flow/multiline','create_po',{source_pr:pr.documentNumber,vendor,purchasing_organization:porg,unit_prices:{'10':50}});await post('/api/procurement-flow/multiline','post_gr',{source_po:po.documentNumber,posting_date:today,document_date:today,movement_type:'101',items:[{line_number:10,received_quantity:3,storage_location:storage}]});
      const so=await post('/api/sales-flow','create_sales_order',{customer,plant,material:mat,quantity:2,unit_price:150});const delivery=await post('/api/sales-flow','create_delivery',{sales_order:so.documentNumber,storage_location:storage});await post('/api/sales-flow','post_goods_issue',{delivery:delivery.documentNumber});const bill=await post('/api/sales-flow','create_billing',{delivery:delivery.documentNumber});const fi=await post('/api/sales-flow','post_receivable',{billing:bill.documentNumber});
      const wrongAmount=await post('/api/customer-payment','post_payment',{receivable_fi:fi.documentNumber,payment_amount:299,payment_date:today,bank_reference:`UTR-WRONG-${Date.now()}`},409);const payment=await post('/api/customer-payment','post_payment',{receivable_fi:fi.documentNumber,payment_amount:300,payment_date:today,bank_reference:`UTR-${Date.now()}`});const duplicatePayment=await post('/api/customer-payment','post_payment',{receivable_fi:fi.documentNumber,payment_amount:300,payment_date:today,bank_reference:`UTR-DUP-${Date.now()}`},409);const reversal=await post('/api/customer-payment','reverse_payment',{payment_document:payment.documentNumber});
      const deactivated=await post('/api/customer-master','deactivate',{customer_code:customer});const inactiveOrder=await post('/api/sales-flow','create_sales_order',{customer,plant,material:mat,quantity:1,unit_price:100},400);
      return{invalidCustomer,created,duplicateCustomer,fi,wrongAmount,payment,duplicatePayment,reversal,deactivated,inactiveOrder};
    });
    expect(result.invalidCustomer.error).toMatch(/not an active customer master/i);expect(result.created.status).toBe('active');expect(result.duplicateCustomer.error).toMatch(/already exists/i);expect(result.fi.clearingStatus).toBe('open');expect(result.wrongAmount.error).toMatch(/full-item clearing only/i);expect(result.payment.clearingStatus).toBe('cleared');expect(result.payment.balanced).toBe(true);expect(result.payment.items).toEqual(expect.arrayContaining([expect.objectContaining({account:'110000',debit:300}),expect.objectContaining({account:'120000',credit:300})]));expect(result.duplicatePayment.error).toMatch(/already cleared|already clears/i);expect(result.reversal.clearingStatus).toBe('open');expect(result.reversal.openCustomerAmount).toBe(300);expect(result.deactivated.status).toBe('inactive');expect(result.inactiveOrder.error).toMatch(/not an active customer master/i);
  });
});
