import { test, expect } from '@playwright/test';

test.describe('O2C dependency integrity',()=>{
  test('enforces payment → FI → billing → PGI → delivery reversal order',async({page},testInfo)=>{
    test.skip(testInfo.project.name!=='chromium','Lifecycle certification runs once on desktop.');test.setTimeout(120000);
    const email=process.env.E2E_LEARNER_EMAIL,password=process.env.E2E_LEARNER_PASSWORD;test.skip(!email||!password,'Requires CI learner.');
    await page.goto('/auth');await page.getByLabel('Email').fill(email!);await page.getByLabel('Password').fill(password!);await page.getByRole('button',{name:'Sign in'}).last().click();await expect(page).toHaveURL(/\/dashboard$/,{timeout:20000});
    const r=await page.evaluate(async()=>{
      const token=JSON.parse(localStorage.getItem('erp-edu-session')||'{}').access_token;if(!token)throw new Error('Missing token');const headers={'Content-Type':'application/json',Authorization:`Bearer ${token}`};
      async function post(url:string,action:string,data:Record<string,unknown>,expected=200){const res=await fetch(url,{method:'POST',headers,body:JSON.stringify({action,data})});const body=await res.json();if(res.status!==expected)throw new Error(`${action} ${res.status}: ${JSON.stringify(body)}`);return body;}
      const state=await fetch('/api/erp-runtime',{headers:{Authorization:headers.Authorization}}).then(x=>x.json());const m=state.masterData??[];const mat=m.find((x:Record<string,unknown>)=>x.entity_type==='material')?.code,plant=m.find((x:Record<string,unknown>)=>x.entity_type==='plant')?.code,vendor=m.find((x:Record<string,unknown>)=>x.entity_type==='vendor')?.code,porg=m.find((x:Record<string,unknown>)=>x.entity_type==='purchasing_organization')?.code,storage=m.find((x:Record<string,unknown>)=>x.entity_type==='storage_location')?.code;if(!mat||!plant||!vendor||!porg||!storage)throw new Error('Missing masters');const today=new Date().toISOString().slice(0,10),customer=`CUST-${Date.now().toString().slice(-6)}`;
      await post('/api/customer-master','create',{customer_code:customer,name:'Dependency Customer',currency:'INR',payment_terms:'NET30',credit_limit:10000});
      const pr=await post('/api/procurement-flow','create_pr',{plant,material:mat,quantity:2});const po=await post('/api/procurement-flow','create_po',{source_pr:pr.documentNumber,vendor,purchasing_organization:porg,unit_price:50});await post('/api/procurement-flow','post_gr',{source_po:po.documentNumber,posting_date:today,document_date:today,movement_type:'101',received_quantity:2,storage_location:storage});
      const so=await post('/api/sales-flow','create_sales_order',{customer,plant,material:mat,quantity:2,unit_price:125});const delivery=await post('/api/sales-flow','create_delivery',{sales_order:so.documentNumber,storage_location:storage});await post('/api/sales-flow','post_goods_issue',{delivery:delivery.documentNumber});const bill=await post('/api/sales-flow','create_billing',{delivery:delivery.documentNumber});const fi=await post('/api/sales-flow','post_receivable',{billing:bill.documentNumber});const payment=await post('/api/customer-payment','post_payment',{receivable_fi:fi.documentNumber,payment_amount:250,payment_date:today,bank_reference:`UTR-${Date.now()}`});
      const fiBlocked=await post('/api/accounting-impact','reverse_fi',{fi_document:fi.documentNumber},409);const billBlocked=await post('/api/sales-flow/dependency','reverse_billing',{billing:bill.documentNumber},409);const pgiBlocked=await post('/api/sales-flow/dependency','reverse_goods_issue',{delivery:delivery.documentNumber},409);
      const payRev=await post('/api/customer-payment','reverse_payment',{payment_document:payment.documentNumber});const fiRev=await post('/api/accounting-impact','reverse_fi',{fi_document:fi.documentNumber});const billRev=await post('/api/sales-flow/dependency','reverse_billing',{billing:bill.documentNumber});const pgiRev=await post('/api/sales-flow/dependency','reverse_goods_issue',{delivery:delivery.documentNumber});const cancel=await post('/api/sales-flow/dependency','cancel_delivery',{delivery:delivery.documentNumber});
      return{fiBlocked,billBlocked,pgiBlocked,payRev,fiRev,billRev,pgiRev,cancel};
    });
    expect(r.fiBlocked.error).toMatch(/reverse the customer payment/i);expect(r.billBlocked.error).toMatch(/reverse FI document/i);expect(r.pgiBlocked.error).toMatch(/reverse billing document/i);expect(r.payRev.clearingStatus).toBe('open');expect(r.fiRev.status).toBe('reversed');expect(r.billRev.status).toBe('reversed');expect(r.pgiRev.status).toBe('open');expect(r.pgiRev.reversalMovementType).toBe('602');expect(r.pgiRev.inventoryAfter-r.pgiRev.inventoryBefore).toBe(2);expect(r.cancel.status).toBe('reversed');expect(r.cancel.salesOrderStatus).toBe('open');
  });
});
