import { test, expect } from '@playwright/test';

test.describe('Order-to-cash foundation',()=>{
  test('moves stock from MM receipt through SO, delivery, PGI, billing and customer receivable',async({page},testInfo)=>{
    test.skip(testInfo.project.name!=='chromium','Lifecycle certification runs once on desktop.');test.setTimeout(120000);
    const email=process.env.E2E_LEARNER_EMAIL,password=process.env.E2E_LEARNER_PASSWORD;test.skip(!email||!password,'Requires CI learner.');
    await page.goto('/auth');await page.getByLabel('Email').fill(email!);await page.getByLabel('Password').fill(password!);await page.getByRole('button',{name:'Sign in'}).last().click();await expect(page).toHaveURL(/\/dashboard$/,{timeout:20000});
    const result=await page.evaluate(async()=>{
      const token=JSON.parse(localStorage.getItem('erp-edu-session')||'{}').access_token;if(!token)throw new Error('Missing token');const headers={'Content-Type':'application/json',Authorization:`Bearer ${token}`};
      async function post(url:string,action:string,data:Record<string,unknown>,expected=200){const r=await fetch(url,{method:'POST',headers,body:JSON.stringify({action,data})});const b=await r.json();if(r.status!==expected)throw new Error(`${action} ${r.status}: ${JSON.stringify(b)}`);return b;}
      async function runtime(){return fetch('/api/erp-runtime',{headers:{Authorization:headers.Authorization}}).then(r=>r.json());}
      const state=await runtime();const m=state.masterData??[];const mats=m.filter((x:Record<string,unknown>)=>x.entity_type==='material').slice(0,2);const plant=m.find((x:Record<string,unknown>)=>x.entity_type==='plant')?.code,vendor=m.find((x:Record<string,unknown>)=>x.entity_type==='vendor')?.code,porg=m.find((x:Record<string,unknown>)=>x.entity_type==='purchasing_organization')?.code,storage=m.find((x:Record<string,unknown>)=>x.entity_type==='storage_location')?.code;if(mats.length<2||!plant||!vendor||!porg||!storage)throw new Error('Missing masters');const today=new Date().toISOString().slice(0,10),customer=`CUST-${Date.now().toString().slice(-6)}`;
      await post('/api/customer-master','create',{customer_code:customer,name:'Phase 5A Test Customer',currency:'INR',payment_terms:'NET30',credit_limit:50000});
      const pr=await post('/api/procurement-flow/multiline','create_pr',{plant,items:[{line_number:10,material:mats[0].code,quantity:10},{line_number:20,material:mats[1].code,quantity:1}]});const po=await post('/api/procurement-flow/multiline','create_po',{source_pr:pr.documentNumber,vendor,purchasing_organization:porg,unit_prices:{'10':50,'20':10}});await post('/api/procurement-flow/multiline','post_gr',{source_po:po.documentNumber,posting_date:today,document_date:today,movement_type:'101',items:[{line_number:10,received_quantity:10,storage_location:storage},{line_number:20,received_quantity:1,storage_location:storage}]});
      const afterReceipt=await runtime();const available=Number((afterReceipt.inventory??[]).find((x:Record<string,unknown>)=>x.material_code===mats[0].code&&x.plant_code===plant&&x.storage_location_code===storage)?.quantity??0);const insufficient=await post('/api/sales-flow','create_sales_order',{customer,plant,material:mats[0].code,quantity:available+1,unit_price:80,currency:'INR'});const insufficientDelivery=await post('/api/sales-flow','create_delivery',{sales_order:insufficient.documentNumber,storage_location:storage},409);
      const so=await post('/api/sales-flow','create_sales_order',{customer,plant,material:mats[0].code,quantity:4,unit_price:80,currency:'INR'});const delivery=await post('/api/sales-flow','create_delivery',{sales_order:so.documentNumber,storage_location:storage});const pgi=await post('/api/sales-flow','post_goods_issue',{delivery:delivery.documentNumber});const duplicatePgi=await post('/api/sales-flow','post_goods_issue',{delivery:delivery.documentNumber},409);const bill=await post('/api/sales-flow','create_billing',{delivery:delivery.documentNumber});const duplicateBill=await post('/api/sales-flow','create_billing',{delivery:delivery.documentNumber},409);const fi=await post('/api/sales-flow','post_receivable',{billing:bill.documentNumber});const duplicateFi=await post('/api/sales-flow','post_receivable',{billing:bill.documentNumber});return{insufficientDelivery,so,delivery,pgi,duplicatePgi,bill,duplicateBill,fi,duplicateFi};
    });
    expect(result.insufficientDelivery.error).toMatch(/insufficient stock/i);expect(result.so.netValue).toBe(320);expect(result.delivery.status).toBe('open');expect(result.pgi.status).toBe('goods_issued');expect(result.pgi.movementType).toBe('601');expect(result.pgi.inventoryAfter).toBe(result.pgi.inventoryBefore-4);expect(result.duplicatePgi.error).toMatch(/cannot post goods issue again/i);expect(result.bill.billingValue).toBe(320);expect(result.duplicateBill.error).toMatch(/already exists/i);expect(result.fi.balanced).toBe(true);expect(result.fi.clearingStatus).toBe('open');expect(result.fi.items).toEqual(expect.arrayContaining([expect.objectContaining({account:'120000',debit:320}),expect.objectContaining({account:'400000',credit:320})]));expect(result.duplicateFi.duplicate).toBe(true);expect(result.duplicateFi.documentNumber).toBe(result.fi.documentNumber);
  });
});
