import { test, expect } from '@playwright/test';

test.describe('P2P dependency integrity',()=>{
  test('enforces downstream-first reversal from payment back to goods receipt',async({page},testInfo)=>{
    test.skip(testInfo.project.name!=='chromium','Lifecycle certification runs once on desktop.');test.setTimeout(120000);
    const email=process.env.E2E_LEARNER_EMAIL,password=process.env.E2E_LEARNER_PASSWORD;test.skip(!email||!password,'Requires CI learner.');
    await page.goto('/auth');await page.getByLabel('Email').fill(email!);await page.getByLabel('Password').fill(password!);await page.getByRole('button',{name:'Sign in'}).last().click();await expect(page).toHaveURL(/\/dashboard$/,{timeout:20000});
    const r=await page.evaluate(async()=>{
      const token=JSON.parse(localStorage.getItem('erp-edu-session')||'{}').access_token;if(!token)throw new Error('Missing token');const headers={'Content-Type':'application/json',Authorization:`Bearer ${token}`};
      async function post(url:string,action:string,data:Record<string,unknown>,expected=200){const res=await fetch(url,{method:'POST',headers,body:JSON.stringify({action,data})});const body=await res.json();if(res.status!==expected)throw new Error(`${action} ${res.status}: ${JSON.stringify(body)}`);return body;}
      const state=await fetch('/api/erp-runtime',{headers:{Authorization:headers.Authorization}}).then(x=>x.json());const masters=state.masterData??[];const mats=masters.filter((x:Record<string,unknown>)=>x.entity_type==='material').slice(0,2);const plant=masters.find((x:Record<string,unknown>)=>x.entity_type==='plant')?.code,vendor=masters.find((x:Record<string,unknown>)=>x.entity_type==='vendor')?.code,porg=masters.find((x:Record<string,unknown>)=>x.entity_type==='purchasing_organization')?.code,storage=masters.find((x:Record<string,unknown>)=>x.entity_type==='storage_location')?.code;if(mats.length<2||!plant||!vendor||!porg||!storage)throw new Error('Missing masters');const today=new Date().toISOString().slice(0,10);
      const pr=await post('/api/procurement-flow/controlled','create_pr',{plant,items:[{line_number:10,material:mats[0].code,quantity:1},{line_number:20,material:mats[1].code,quantity:2}]});await post('/api/procurement-flow/approvals','submit',{document_number:pr.documentNumber,acting_role:'requester'});await post('/api/procurement-flow/approvals','approve',{document_number:pr.documentNumber,acting_role:'department_manager'});
      const po=await post('/api/procurement-flow/controlled','create_po',{source_pr:pr.documentNumber,vendor,purchasing_organization:porg,unit_prices:{'10':200,'20':75}});await post('/api/procurement-flow/approvals','submit',{document_number:po.documentNumber,acting_role:'buyer'});await post('/api/procurement-flow/approvals','approve',{document_number:po.documentNumber,acting_role:'purchasing_manager'});
      const gr=await post('/api/procurement-flow/controlled','post_gr',{source_po:po.documentNumber,posting_date:today,document_date:today,movement_type:'101',items:[{line_number:10,received_quantity:1,storage_location:storage},{line_number:20,received_quantity:2,storage_location:storage}]});
      const iv=await post('/api/procurement-flow/multiline','post_invoice',{source_po:po.documentNumber,supplier_invoice_number:`P2P-${Date.now()}`,invoice_date:today,posting_date:today,invoice_value:350});const grFi=await post('/api/accounting-impact','post_source',{source_document:gr.documentNumber});const ivFi=await post('/api/accounting-impact','post_source',{source_document:iv.documentNumber});const payment=await post('/api/vendor-payment','post_payment',{invoice_fi:ivFi.documentNumber,payment_amount:350,payment_date:today,bank_reference:`UTR-${Date.now()}`});
      const fiBlocked=await post('/api/accounting-impact','reverse_fi',{fi_document:ivFi.documentNumber},409);const ivBlocked=await post('/api/procurement-flow/dependency','reverse_invoice',{source_invoice:iv.documentNumber},409);const grBlocked=await post('/api/procurement-flow/dependency','reverse_gr',{source_gr:gr.documentNumber},409);
      const payRev=await post('/api/vendor-payment','reverse_payment',{payment_document:payment.documentNumber});const fiRev=await post('/api/accounting-impact','reverse_fi',{fi_document:ivFi.documentNumber});const ivRev=await post('/api/procurement-flow/dependency','reverse_invoice',{source_invoice:iv.documentNumber});const grStillFi=await post('/api/procurement-flow/dependency','reverse_gr',{source_gr:gr.documentNumber},409);const grFiRev=await post('/api/accounting-impact','reverse_fi',{fi_document:grFi.documentNumber});const grRev=await post('/api/procurement-flow/dependency','reverse_gr',{source_gr:gr.documentNumber});
      return {fiBlocked,ivBlocked,grBlocked,payRev,fiRev,ivRev,grStillFi,grFiRev,grRev};
    });
    expect(r.fiBlocked.error).toMatch(/reverse the vendor payment/i);expect(r.ivBlocked.error).toMatch(/reverse FI document/i);expect(r.grBlocked.error).toMatch(/reverse FI document/i);expect(r.payRev.clearingStatus).toBe('open');expect(r.fiRev.status).toBe('reversed');expect(r.ivRev.status).toBe('reversed');expect(r.grStillFi.error).toMatch(/reverse FI document/i);expect(r.grFiRev.status).toBe('reversed');expect(r.grRev.status).toBe('reversed');expect(r.grRev.poStatus).toBe('open');
  });
});
