import { test, expect } from '@playwright/test';

function workLabEmail(base:string){const at=base.lastIndexOf('@');return at>0?`${base.slice(0,at)}+worklab${base.slice(at)}`:`${base}+worklab`;}
async function signIn(page:import('@playwright/test').Page){const base=process.env.E2E_LEARNER_EMAIL,password=process.env.E2E_LEARNER_PASSWORD;test.skip(!base||!password,'Requires Erpedu CI learner.');await page.goto('/auth');await page.getByLabel('Email').fill(workLabEmail(base!));await page.getByLabel('Password').fill(password!);await page.getByRole('button',{name:'Sign in'}).last().click();await expect(page).toHaveURL(/\/dashboard$/,{timeout:20000});}
async function token(page:import('@playwright/test').Page){return page.evaluate(()=>{const raw=localStorage.getItem('erp-edu-session');if(!raw)throw new Error('Missing session');const s=JSON.parse(raw);if(!s.access_token)throw new Error('Missing token');return s.access_token as string;});}

test.describe('Phase 6D workplace inbox',()=>{
 test('aggregates work items and persists idempotent acknowledgement',async({page,request},testInfo)=>{test.skip(testInfo.project.name!=='chromium','Durable acknowledgement lifecycle runs once on desktop.');await signIn(page);const t=await token(page),headers={Authorization:`Bearer ${t}`};const first=await request.get('/api/workplace-inbox',{headers});expect(first.ok()).toBeTruthy();const inbox=await first.json();expect(inbox.items.length).toBeGreaterThan(0);expect(inbox.summary.open+inbox.summary.acknowledged+inbox.summary.completed).toBe(inbox.items.length);const open=inbox.items.find((x:any)=>x.status==='open');expect(open).toBeTruthy();const ack=await request.post('/api/workplace-inbox',{headers,data:{itemKey:open.key}});expect(ack.ok()).toBeTruthy();expect((await ack.json()).duplicate).toBe(false);const duplicate=await request.post('/api/workplace-inbox',{headers,data:{itemKey:open.key}});expect(duplicate.ok()).toBeTruthy();expect((await duplicate.json()).duplicate).toBe(true);const after=await request.get('/api/workplace-inbox',{headers});const next=await after.json();expect(next.items).toEqual(expect.arrayContaining([expect.objectContaining({key:open.key,status:'acknowledged'})]));});
 test('workplace inbox is reachable and actionable on the configured viewport',async({page})=>{await signIn(page);await page.goto('/work-lab/inbox');await expect(page.getByRole('heading',{name:'Your ERP work queue'})).toBeVisible();await expect(page.locator('[data-inbox-item]').first()).toBeVisible();await expect(page.getByRole('link',{name:/Open work item|Review/}).first()).toBeVisible();});
});
