"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { authenticatedFetch } from "../../../lib/auth-client";

type Item={key:string;kind:"work_ticket"|"exception";title:string;description:string;priority:"high"|"normal"|"low";dueAt:string;status:"open"|"acknowledged"|"completed";actionUrl:string;linkedDocument:string|null};
type Data={items:Item[];summary:{open:number;acknowledged:number;completed:number;exceptions:number}};

export default function WorkplaceInboxPage(){const [data,setData]=useState<Data|null>(null);const [message,setMessage]=useState("");const [busy,setBusy]=useState<string|null>(null);useEffect(()=>{void load();},[]);async function load(){const r=await authenticatedFetch("/api/workplace-inbox");const p=await r.json();if(!r.ok){setMessage(p.error??"Unable to load workplace inbox.");return;}setData(p as Data);setMessage("");}async function acknowledge(key:string){setBusy(key);try{const r=await authenticatedFetch("/api/workplace-inbox",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({itemKey:key})});const p=await r.json();if(!r.ok){setMessage(p.error??"Unable to acknowledge work item.");return;}await load();}finally{setBusy(null);}}return <main className="dashboardPage"><header className="dashboardTopbar"><Link href="/dashboard" className="brandLink">ERP Edu · Workplace Inbox</Link><div className="courseTopActions"><Link href="/work-lab/manager-review" className="primaryButton">Manager Review</Link><Link href="/work-lab" className="secondaryButton">Work Lab</Link><Link href="/work-lab/incidents" className="secondaryButton">Incident Lab</Link></div></header><section className="dashboardHero"><div><span className="eyebrow">Phase 6D · simulated workday</span><h1>Your ERP work queue</h1><p>Prioritize normal transactions and exceptions the way an ERP user would during a real shift.</p></div></section>{message&&<article className="workGateCard locked"><h2>{message}</h2></article>}{data&&<><section className="dashboardStats"><article><strong>{data.summary.open}</strong><span>Open</span></article><article><strong>{data.summary.acknowledged}</strong><span>Acknowledged</span></article><article><strong>{data.summary.exceptions}</strong><span>Exceptions</span></article><article><strong>{data.summary.completed}</strong><span>Completed</span></article></section><section className="dashboardGrid" style={{gridTemplateColumns:"1fr"}}>{data.items.map(item=><article className="dashboardCourseCard" key={item.key} data-inbox-item={item.key}><span className="courseBadge">{item.priority.toUpperCase()} · {item.kind==="exception"?"Exception":"Work ticket"}</span><h2>{item.title}</h2><p>{item.description}</p><p><strong>Status:</strong> {item.status} · <strong>Due:</strong> {new Date(item.dueAt).toLocaleString()}{item.linkedDocument?<> · <strong>Document:</strong> {item.linkedDocument}</>:null}</p><div className="courseTopActions">{item.status==="open"&&<button className="secondaryButton" type="button" disabled={busy===item.key} onClick={()=>void acknowledge(item.key)}>{busy===item.key?"Acknowledging…":"Acknowledge"}</button>}<Link className="primaryButton" href={item.actionUrl}>{item.status==="completed"?"Review":"Open work item"}</Link></div></article>)}</section></>}</main>;}
