import { NextResponse } from "next/server";
import { getSupabaseUser, supabaseRest } from "../../../lib/supabase";

type Doc={id:string;document_number:string;document_type:string;status:string;header:Record<string,unknown>;items:Array<Record<string,unknown>>;created_at:string};
function tokenOf(r:Request){const a=r.headers.get("authorization");return a?.startsWith("Bearer ")?a.slice(7):undefined;}
function num(v:unknown){const n=Number(v??0);return Number.isFinite(n)?n:0;}
async function state(userId:string,token:string){const [profiles,reviews,work,incidents,acks]=await Promise.all([
 supabaseRest<Doc[]>(`erp_documents?user_id=eq.${userId}&document_type=eq.COMPETENCY_PROFILE&select=id,document_number,document_type,status,header,items,created_at&order=created_at.desc&limit=1`,{},token),
 supabaseRest<Doc[]>(`erp_documents?user_id=eq.${userId}&document_type=eq.MANAGER_REVIEW&select=id,document_number,document_type,status,header,items,created_at&order=created_at.desc&limit=1`,{},token),
 supabaseRest<Array<{result:string;score:number}>>(`work_lab_attempts?user_id=eq.${userId}&select=result,score`,{},token),
 supabaseRest<Array<{result:string;score:number}>>(`work_lab_incident_attempts?user_id=eq.${userId}&select=result,score`,{},token),
 supabaseRest<Doc[]>(`erp_documents?user_id=eq.${userId}&document_type=eq.WORK_INBOX_ACK&select=id,document_number,document_type,status,header,items,created_at`,{},token),
 ]);const profile=profiles[0],review=reviews[0];const overall=profile?num(profile.header.overall):0,recommendation=String(review?.header.recommendation??"");const checks={competencyProfile:Boolean(profile),managerReview:Boolean(review),minimumOverall:overall>=70,workTicketPassed:work.some(x=>x.result==="pass"),incidentPassed:incidents.some(x=>x.result==="pass"),workplaceTriaged:acks.length>0,managerRecommendation:["recommended","recommended_with_supervision"].includes(recommendation)};const eligible=Object.values(checks).every(Boolean);return {eligible,checks,overall,recommendation,profileDocument:profile?.document_number??null,managerReviewDocument:review?.document_number??null};}
export async function GET(request:Request){const token=tokenOf(request);if(!token)return NextResponse.json({error:"Authentication required"},{status:401});const user=await getSupabaseUser(token);if(!user)return NextResponse.json({error:"Invalid session"},{status:401});return NextResponse.json(await state(user.id,token));}
export async function POST(request:Request){const token=tokenOf(request);if(!token)return NextResponse.json({error:"Authentication required"},{status:401});const user=await getSupabaseUser(token);if(!user)return NextResponse.json({error:"Invalid session"},{status:401});const current=await state(user.id,token);if(!current.eligible)return NextResponse.json({error:"Final workplace certification requirements are not yet complete.",...current},{status:409});const doc=`CAP-${user.id.slice(0,8).toUpperCase()}`;const existing=await supabaseRest<Doc[]>(`erp_documents?user_id=eq.${user.id}&document_type=eq.FINAL_WORKPLACE_CERTIFICATION&document_number=eq.${doc}&select=id,document_number,document_type,status,header,items,created_at&limit=1`,{},token);const payload={status:"certified",header:{...current,certified_at:new Date().toISOString(),training_phase:"6F",certification_label:"ERP Edu Workplace Certified — SAP MM Level 1"},items:Object.entries(current.checks).map(([requirement,passed])=>({requirement,passed}))};if(existing[0])await supabaseRest(`erp_documents?id=eq.${existing[0].id}&user_id=eq.${user.id}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify(payload)},token);else await supabaseRest("erp_documents",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({user_id:user.id,document_type:"FINAL_WORKPLACE_CERTIFICATION",document_number:doc,...payload})},token);return NextResponse.json({certified:true,documentNumber:doc,updated:Boolean(existing[0]),...current});}
