"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { getStoredSession } from "../../lib/auth-client";

type Task={id:string;title:string;description:string;task_type:string;difficulty:string};
type Attempt={id:string;task_id:string;score:number;result:string;ai_help_count:number;started_at:string;completed_at:string|null};
type Data={unlocked:boolean;tasks:Task[];attempts:Attempt[]};
type Result={passed:boolean;percentage:number;feedback:string;independenceScore:number};
type CoachResult={reply?:string;error?:string};
type UiField={key:string;label:string;type:"text"|"number"};

export default function WorkLabPage(){
  const [data,setData]=useState<Data|null>(null);const [fields,setFields]=useState<UiField[]>([]);const [values,setValues]=useState<Record<string,string>>({});const [result,setResult]=useState<Result|null>(null);const [aiHelp,setAiHelp]=useState(0);const [message,setMessage]=useState("");const [coach,setCoach]=useState("");
  useEffect(()=>{void load();},[]);
  async function load(){const session=getStoredSession();if(!session){window.location.href="/auth";return;}const response=await fetch("/api/work-lab",{headers:{Authorization:`Bearer ${session.access_token}`}});if(response.status===403){setMessage("Work Lab is locked until SAP MM Level 1 is 100% complete.");return;}const payload=await response.json();if(!response.ok){setMessage(payload.error??"Unable to load Work Lab.");return;}const next=payload as Data;setData(next);const task=next.tasks[0];if(task){const ui=await fetch(`/api/work-lab-ui?taskId=${task.id}`).then(r=>r.json()) as {fields:UiField[]};setFields(ui.fields??[]);}}
  function answer(){return Object.fromEntries(fields.map(f=>[f.key,f.type==="number"?Number(values[f.key]||0):(values[f.key]??"").trim()]));}
  async function submit(event:FormEvent){event.preventDefault();const session=getStoredSession();const task=data?.tasks[0];if(!session||!task)return;const response=await fetch("/api/work-lab",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({taskId:task.id,answer:answer(),aiHelpCount:aiHelp})});const payload=await response.json();if(!response.ok){setMessage(payload.error??"Unable to verify task.");return;}setResult(payload as Result);setMessage("");await load();}
  async function askWorkAssistant(){const session=getStoredSession();const task=data?.tasks[0];if(!session||!task)return;const response=await fetch("/api/coach",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({mode:"work",taskId:task.id,hintLevel:1,prompt:"I need help investigating this ticket. Guide me without giving me the final transaction values."})});const payload=await response.json() as CoachResult;if(!response.ok){setCoach(payload.error??"Work assistant unavailable.");return;}setAiHelp(n=>n+1);setCoach(payload.reply??"Review the business request one field at a time.");}
  const task=data?.tasks[0];const taskAttempts=task?(data?.attempts??[]).filter(a=>a.task_id===task.id):[];const hasInput=fields.some(f=>(values[f.key]??"").trim());
  return <main className="dashboardPage"><header className="dashboardTopbar"><Link href="/dashboard" className="brandLink">ERP Edu · Work Lab</Link><Link href="/dashboard" className="secondaryButton">Back to dashboard</Link></header><section className="dashboardHero"><div><span className="eyebrow">Simulated SAP workplace</span><h1>Do the work, not another lesson.</h1><p>Guidance is reduced here. Your accuracy and independence become part of your work record.</p></div></section>{message&&<article className="workGateCard locked"><h2>{message}</h2><Link className="primaryButton" href="/courses/sap-mm-level-1">Return to course</Link></article>}{task&&<section className="dashboardGrid"><article className="dashboardCourseCard"><span className="courseBadge">{task.difficulty} · {task.task_type}</span><h2>{task.title}</h2><p>{task.description}</p><p><strong>Manager note:</strong> Complete the transaction correctly. Assistance lowers your independence score.</p></article><div className="dashboardStats"><article><strong>{taskAttempts.length}</strong><span>Attempts</span></article><article><strong>{taskAttempts[0]?.score??0}%</strong><span>Latest accuracy</span></article><article><strong>{taskAttempts.reduce((s,a)=>s+a.ai_help_count,0)}</strong><span>AI assists</span></article><article><strong>{taskAttempts.some(a=>a.result==="pass")?"Yes":"No"}</strong><span>Verified</span></article></div></section>}{task&&<section className="dashboardLowerGrid"><article className="nextStepCard"><span className="eyebrow">Work ticket transaction</span><h2>Complete the document</h2><form onSubmit={submit} className="erpWorkspace"><div className="erpWindowBar"><strong>MM Work Transaction</strong><span>Employee simulation · Scored</span></div><div className="erpFieldGrid">{fields.map(field=><label key={field.key}><span>{field.label}</span><input type={field.type} value={values[field.key]??""} onChange={e=>setValues(v=>({...v,[field.key]:e.target.value}))}/></label>)}</div><div className="erpActionBar"><button className="primaryButton" disabled={!hasInput}>Post & Verify</button><button type="button" className="secondaryButton" onClick={askWorkAssistant}>Ask work assistant</button></div></form>{coach&&<div className="coachNote"><p><strong>Work assistant:</strong> {coach}</p></div>}</article><article className={`workGateCard ${result?.passed?"unlocked":"locked"}`}><span className="eyebrow">Performance</span><h2>{result?`${result.percentage}% accuracy`:"Awaiting submission"}</h2><p>{result?.feedback??"Submit the ticket to create your verified Work Lab record."}</p>{result&&<span className="workGateStatus">Independence score: {result.independenceScore}%</span>}</article></section>}</main>;
}
