import { NextResponse } from "next/server";
import { getSupabaseUser, supabaseRest } from "../../../lib/supabase";

type Doc={id:string;document_number:string;document_type:string;status:string;header:Record<string,unknown>;items:Array<Record<string,unknown>>;created_at:string};
type Attempt={score:number;result?:string;status?:string;ai_help_count?:number};
type Certificate={certificate_type:string;verification_code:string;score:number;issued_at:string;is_public:boolean};
function tokenOf(r:Request){const a=r.headers.get("authorization");return a?.startsWith("Bearer ")?a.slice(7):undefined;}
function num(v:unknown){const n=Number(v??0);return Number.isFinite(n)?n:0;}
function recommendation(overall:number,jobReady:boolean,incidentsResolved:number,workPassed:number){if(jobReady&&overall>=85&&incidentsResolved>0&&workPassed>0)return "recommended";if(overall>=70)return "recommended_with_supervision";return "not_yet_ready";}
async function build(userId:string,token:string){const [profiles,work,incidents,acks,certs]=await Promise.all([
 supabaseRest<Doc[]>(`erp_documents?user_id=eq.${userId}&document_type=eq.COMPETENCY_PROFILE&select=id,document_number,document_type,status,header,items,created_at&order=created_at.desc&limit=1`,{},token),
 supabaseRest<Attempt[]>(`work_lab_attempts?user_id=eq.${userId}&select=score,result,ai_help_count`,{},token),
 supabaseRest<Attempt[]>(`work_lab_incident_attempts?user_id=eq.${userId}&select=score,result,ai_help_count`,{},token),
 supabaseRest<Doc[]>(`erp_documents?user_id=eq.${userId}&document_type=eq.WORK_INBOX_ACK&select=id,document_number,document_type,status,header,items,created_at`,{},token),
 supabaseRest<Certificate[]>(`certificates?user_id=eq.${userId}&select=certificate_type,verification_code,score,issued_at,is_public&order=issued_at.desc`,{},token),
 ]);const profile=profiles[0];if(!profile)throw new Error("Competency profile not found. Recalculate skills profile first.");const h=profile.header;const overall=num(h.overall),jobReady=String(profile.status)==="job_ready"||String(h.readinessBand)==="certified";const workPassed=work.filter(x=>x.result==="pass").length,incidentsResolved=incidents.filter(x=>x.result==="pass").length;const rec=recommendation(overall,jobReady,incidentsResolved,workPassed);return {profileDocument:profile.document_number,overall,level:String(h.level??""),readinessBand:String(h.readinessBand??""),jobReady,recommendation:rec,skills:{courseScore:num(h.courseScore),transactionAccuracy:num(h.transactionAccuracy),trainingIndependence:num(h.trainingIndependence),practicalScore:num(h.practicalScore),incidentScore:num(h.incidentScore),assessmentScore:num(h.assessmentScore)},evidence:{workAttempts:work.length,workPassed,incidentAttempts:incidents.length,incidentsResolved,inboxAcknowledgements:acks.length,certificates:certs.length},certificates:certs.filter(c=>c.is_public)};}
export async function GET(request:Request){const token=tokenOf(request);if(!token)return NextResponse.json({error:"Authentication required"},{status:401});const user=await getSupabaseUser(token);if(!user)return NextResponse.json({error:"Invalid session"},{status:401});try{return NextResponse.json(await build(user.id,token));}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unable to build manager review."},{status:404});}}
export async function POST(request:Request){const token=tokenOf(request);if(!token)return NextResponse.json({error:"Authentication required"},{status:401});const user=await getSupabaseUser(token);if(!user)return NextResponse.json({error:"Invalid session"},{status:401});try{const review=await build(user.id,token),doc=`MGR-${user.id.slice(0,8).toUpperCase()}`;const existing=await supabaseRest<Doc[]>(`erp_documents?user_id=eq.${user.id}&document_type=eq.MANAGER_REVIEW&document_number=eq.${doc}&select=id,document_number,document_type,status,header,items,created_at&limit=1`,{},token);const payload={status:review.recommendation==="recommended"?"recommended":"review_required",header:{...review,generated_at:new Date().toISOString(),training_phase:"6E"},items:Object.entries(review.skills).map(([skill_key,score])=>({skill_key,score}))};if(existing[0])await supabaseRest(`erp_documents?id=eq.${existing[0].id}&user_id=eq.${user.id}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify(payload)},token);else await supabaseRest("erp_documents",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({user_id:user.id,document_type:"MANAGER_REVIEW",document_number:doc,...payload})},token);return NextResponse.json({saved:true,documentNumber:doc,updated:Boolean(existing[0]),...review});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unable to save manager review."},{status:404});}}
