"use client";

import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { getStoredSession } from "../../lib/auth-client";

type Assessment={id:string;title:string;description:string;durationMinutes:number;passingScore:number;maxAiHelp:number;fields:string[]};
type Attempt={id:string;started_at:string;expires_at:string;status:string;score:number|null;ai_help_count:number;independence_score:number|null};
type Data={eligible:boolean;assessment:Assessment;activeAttempt:Attempt|null;attempts:Attempt[]};
const labels:Record<string,string>={process_sequence:"Process sequence",price_exception_action:"Price exception action",open_quantity:"Open quantity",allowed_receipt:"Allowed receipt quantity",inventory_action:"Inventory action",supported_invoice_value:"Supported invoice value",invoice_status:"Invoice status",support_root_cause:"Support root cause"};

export default function JobReadinessPage(){
 const [data,setData]=useState<Data|null>(null);const [attemptId,setAttemptId]=useState<string|null>(null);const [expiresAt,setExpiresAt]=useState<string|null>(null);const [answers,setAnswers]=useState<Record<string,string>>({});const [message,setMessage]=useState("");const [result,setResult]=useState<{passed:boolean;score:number;independenceScore:number}|null>(null);const [aiHelp,setAiHelp]=useState(0);const [hint,setHint]=useState("");const [now,setNow]=useState(Date.now());
 useEffect(()=>{void load();const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
 async function authFetch(path:string,init:RequestInit={}){const s=getStoredSession();if(!s){window.location.href="/auth";throw new Error("No session");}return fetch(path,{...init,headers:{...(init.headers??{}),Authorization:`Bearer ${s.access_token}`}});}
 async function load(){const r=await authFetch("/api/job-readiness");if(r.status===403){setMessage("Complete SAP MM Level 1 before taking the job-readiness assessment.");return;}const p=await r.json();if(!r.ok){setMessage(p.error??"Unable to load assessment.");return;}setData(p);if(p.activeAttempt){setAttemptId(p.activeAttempt.id);setExpiresAt(p.activeAttempt.expires_at);setAiHelp(p.activeAttempt.ai_help_count??0);}}
 async function action(body:Record<string,unknown>){const r=await authFetch("/api/job-readiness",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const p=await r.json();if(!r.ok){setMessage(p.error??"Assessment action failed.");return null;}setMessage("");return p;}
 async function start(){const p=await action({action:"start"});if(!p)return;setAttemptId(p.attemptId);setExpiresAt(p.expiresAt);setAnswers({});setResult(null);setAiHelp(0);setHint("");}
 async function askHelp(){if(!attemptId)return;const p=await action({action:"ai_help",attemptId});if(!p)return;setAiHelp(p.aiHelpCount);setHint(p.hint);}
 async function submit(){if(!attemptId)return;const numeric=new Set(["open_quantity","allowed_receipt","supported_invoice_value"]);const payload=Object.fromEntries(Object.entries(answers).map(([k,v])=>[k,numeric.has(k)?Number(v):v]));const p=await action({action:"submit",attemptId,answers:payload});if(!p)return;setResult(p);setAttemptId(null);setExpiresAt(null);await load();}
 const remaining=useMemo(()=>expiresAt?Math.max(0,Math.floor((new Date(expiresAt).getTime()-now)/1000)):0,[expiresAt,now]);const mm=String(Math.floor(remaining/60)).padStart(2,"0"),ss=String(remaining%60).padStart(2,"0");
 return <main className="dashboardPage"><header className="dashboardTopbar"><Link href="/dashboard" className="brandLink">ERP Edu · Job Readiness</Link><Link href="/skills" className="secondaryButton">Skills profile</Link></header>
 <section className="dashboardHero"><div><span className="eyebrow">Independent assessment</span><h1>Prove you can work without step-by-step teaching.</h1><p>This assessment is timed and AI help is heavily restricted. Passing means you can reason through core SAP MM foundation scenarios independently.</p></div>{expiresAt&&<div className="dashboardProgress"><strong>{mm}:{ss}</strong><span>Time remaining</span></div>}</section>
 {message&&<article className="workGateCard locked"><p>{message}</p></article>}
 {data&&!attemptId&&!result&&<section className="dashboardGrid"><article className="dashboardCourseCard"><span className="courseBadge">60 min · {data.assessment.passingScore}% pass</span><h2>{data.assessment.title}</h2><p>{data.assessment.description}</p><p><strong>AI allowance:</strong> {data.assessment.maxAiHelp} assist maximum.</p><button className="primaryButton" onClick={start}>Start assessment</button></article><div className="dashboardStats"><article><strong>{data.attempts.length}</strong><span>Attempts</span></article><article><strong>{Math.max(0,...data.attempts.map(a=>a.score??0))}%</strong><span>Best score</span></article><article><strong>{data.attempts.filter(a=>a.status==="passed").length}</strong><span>Passed</span></article><article><strong>{data.attempts[0]?.independence_score??100}%</strong><span>Latest independence</span></article></div></section>}
 {data&&attemptId&&<section className="dashboardLowerGrid"><article className="nextStepCard"><span className="eyebrow">Assessment case</span><h2>Operational procurement exception set</h2><p>Use business process logic. Do not guess from labels; think about what should happen in a controlled procure-to-pay environment.</p><div className="erpFieldGrid">{data.assessment.fields.map(k=><label key={k}><span>{labels[k]??k.replaceAll("_"," ")}</span><input value={answers[k]??""} onChange={e=>setAnswers(v=>({...v,[k]:e.target.value}))}/></label>)}</div><div className="erpActionBar"><button className="primaryButton" onClick={submit} disabled={remaining===0}>Submit assessment</button><button className="secondaryButton" onClick={askHelp} disabled={aiHelp>=data.assessment.maxAiHelp}>Limited AI help ({aiHelp}/{data.assessment.maxAiHelp})</button></div>{hint&&<div className="coachNote"><p><strong>Assessment hint:</strong> {hint}</p></div>}</article><article className="workGateCard unlocked"><span className="eyebrow">Rules</span><h2>No guided retries</h2><p>One timed attempt measures your current ability. Review document flow, quantities, and invoice support before submitting.</p><span className="workGateStatus">Pass mark {data.assessment.passingScore}%</span></article></section>}
 {result&&<article className={`workGateCard ${result.passed?"unlocked":"locked"}`}><span className="eyebrow">Assessment result</span><h2>{result.passed?"Job-readiness gate passed":"More practice required"}</h2><p>Score: {result.score}% · Independence: {result.independenceScore}%</p><div className="exerciseActions"><button className="primaryButton" onClick={()=>{setResult(null);void load();}}>Back to assessment</button><Link className="secondaryButton" href="/skills">Open verified skills</Link></div></article>}
 </main>;
}
