"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { authenticatedFetch } from "../../../lib/auth-client";
type Data={eligible:boolean;checks:Record<string,boolean>;overall:number;recommendation:string;profileDocument:string|null;managerReviewDocument:string|null;certified?:boolean;documentNumber?:string};
export default function FinalCertificationPage(){
 const [data,setData]=useState<Data|null>(null);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);
 useEffect(()=>{void load();},[]);
 async function load(){setLoading(true);try{const r=await authenticatedFetch("/api/final-workplace-certification");const p=await r.json();if(!r.ok){setMessage(p.error??"Unable to load certification.");setData(null);return;}setData(p as Data);setMessage("");}catch{setMessage("Unable to load certification. Check your connection and try again.");setData(null);}finally{setLoading(false);}}
 async function certify(){setBusy(true);setMessage("");try{const r=await authenticatedFetch("/api/final-workplace-certification",{method:"POST"});const p=await r.json();if(!r.ok){setMessage(p.error??"Certification requirements are incomplete.");setData(p as Data);return;}setData(p as Data);setMessage("Final workplace certification recorded.");}catch{setMessage("Unable to record certification. Try again.");}finally{setBusy(false);}}
 return <main className="dashboardPage"><header className="dashboardTopbar"><Link href="/dashboard" className="brandLink">ERP Edu · Final Certification</Link><div className="courseTopActions"><Link href="/work-lab/manager-review" className="secondaryButton">Manager review</Link><Link href="/work-lab/inbox" className="secondaryButton">Workplace inbox</Link></div></header><section className="dashboardHero" aria-labelledby="final-cert-title"><div><span className="eyebrow">Phase 6F · capstone</span><h1 id="final-cert-title">Final workplace certification</h1><p>This gate verifies your complete ERP workplace evidence chain before certification.</p></div></section>{loading&&<section className="statePanel" role="status" aria-live="polite"><h2>Checking certification readiness…</h2><p>We are verifying your workplace evidence and manager review.</p></section>}{message&&<section className="statePanel" role={data?"status":"alert"} aria-live="assertive"><h2>{message}</h2>{!data&&<button type="button" className="secondaryButton" onClick={()=>void load()}>Try again</button>}</section>}{data&&<><section className="dashboardStats" aria-label="Certification readiness summary"><article><strong>{data.overall}%</strong><span>Competency score</span></article><article><strong>{data.eligible?"Ready":"Pending"}</strong><span>Certification gate</span></article><article><strong>{data.recommendation||"—"}</strong><span>Manager recommendation</span></article><article><strong>{Object.values(data.checks).filter(Boolean).length}/{Object.keys(data.checks).length}</strong><span>Requirements met</span></article></section><section className="dashboardGrid" style={{gridTemplateColumns:"1fr"}}><article className="dashboardCourseCard" aria-labelledby="capstone-requirements"><h2 id="capstone-requirements">Capstone requirements</h2><ul className="checkListSemantic">{Object.entries(data.checks).map(([k,v])=><li key={k}><span aria-hidden="true">{v?"✓":"○"}</span><span>{k.replace(/([A-Z])/g," $1")}</span><span className="srOnly">{v?"Requirement met":"Requirement pending"}</span></li>)}</ul><div className="courseTopActions"><button className="primaryButton" type="button" aria-busy={busy} disabled={!data.eligible||busy} onClick={()=>void certify()}>{busy?"Certifying…":data.certified?"Certification recorded":"Record final certification"}</button></div>{data.documentNumber&&<p><strong>Certification record:</strong> {data.documentNumber}</p>}{!data.eligible&&<p className="muted">Complete the pending requirements above, then return here to certify.</p>}</article></section></>}</main>;
}
