import { NextResponse } from "next/server";
import { getSupabaseUser, supabaseRest } from "../../../../lib/supabase";

type ErpDocument={id:string;document_number:string;document_type:string;status:string;header:Record<string,unknown>;items:Array<Record<string,unknown>>;created_at:string};
type MasterRow={entity_type:string;code:string;name:string;attributes:Record<string,unknown>|null;is_active:boolean};
type BalanceRow={quantity:number|string};
type Line={line_number?:number;material?:string;quantity?:number;unit_price?:number;received_quantity?:number;storage_location?:string};
type Body={action?:"create_pr"|"create_po"|"post_gr"|"post_invoice"|"reverse_gr"|"reverse_invoice";data?:Record<string,unknown>};

function tokenOf(request:Request){const auth=request.headers.get("authorization");return auth?.startsWith("Bearer ")?auth.slice(7):undefined;}
function docNumber(prefix:string){return `${prefix}-${Date.now().toString().slice(-9)}`;}
function isoDate(value:unknown){const raw=String(value??"").trim();return /^\d{4}-\d{2}-\d{2}$/.test(raw)?raw:new Date().toISOString().slice(0,10);}
async function findDoc(userId:string,token:string,number:string,type:string){const rows=await supabaseRest<ErpDocument[]>(`erp_documents?user_id=eq.${userId}&document_number=eq.${encodeURIComponent(number)}&document_type=eq.${type}&select=id,document_number,document_type,status,header,items,created_at&limit=1`,{},token);return rows[0]??null;}
async function updateDoc(doc:ErpDocument,status:string,token:string,headerPatch?:Record<string,unknown>){await supabaseRest(`erp_documents?id=eq.${doc.id}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({status,header:headerPatch??doc.header})},token);}
async function master(type:string,code:string,token:string){const rows=await supabaseRest<MasterRow[]>(`erp_master_data?entity_type=eq.${encodeURIComponent(type)}&code=eq.${encodeURIComponent(code)}&is_active=eq.true&select=entity_type,code,name,attributes,is_active&limit=1`,{},token);return rows[0]??null;}
async function requireMaster(type:string,code:string,label:string,token:string){if(!code||!(await master(type,code,token)))throw new Error(`${label} ${code||"(blank)"} is not an active ERP master-data value.`);}
function linkedPlant(row:MasterRow|null){const attrs=row?.attributes??{};return String(attrs.plant_code??attrs.plant??"").trim();}
async function receipts(userId:string,token:string,po:string){return supabaseRest<ErpDocument[]>(`erp_documents?user_id=eq.${userId}&document_type=eq.GR&status=neq.reversed&header->>source_po=eq.${encodeURIComponent(po)}&select=id,document_number,status,header,items,created_at`,{},token);}
async function invoices(userId:string,token:string,po:string){return supabaseRest<ErpDocument[]>(`erp_documents?user_id=eq.${userId}&document_type=eq.IV&status=neq.reversed&header->>source_po=eq.${encodeURIComponent(po)}&select=id,document_number,status,header,items,created_at`,{},token);}
async function balance(userId:string,token:string,material:string,plant:string,storage:string){const rows=await supabaseRest<BalanceRow[]>(`erp_inventory_balances?user_id=eq.${userId}&material_code=eq.${encodeURIComponent(material)}&plant_code=eq.${encodeURIComponent(plant)}&storage_location_code=eq.${encodeURIComponent(storage)}&select=quantity&limit=1`,{},token);return Number(rows[0]?.quantity??0);}
async function setBalance(userId:string,token:string,material:string,plant:string,storage:string,quantity:number){await supabaseRest("erp_inventory_balances?on_conflict=user_id,material_code,plant_code,storage_location_code",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({user_id:userId,material_code:material,plant_code:plant,storage_location_code:storage,quantity,updated_at:new Date().toISOString()})},token);}
function normalizedLines(value:unknown):Line[]{if(!Array.isArray(value))return [];return value.map((raw,index)=>{const row=(raw??{}) as Record<string,unknown>;return {line_number:Number(row.line_number??(index+1)*10),material:String(row.material??"").trim(),quantity:Number(row.quantity??0),unit_price:Number(row.unit_price??0),received_quantity:Number(row.received_quantity??0),storage_location:String(row.storage_location??"SL01").trim()||"SL01"};});}
function receiptTotals(rows:ErpDocument[]){const byLine=new Map<number,number>();for(const row of rows){for(const item of row.items??[]){const line=Number(item.line_number??0);byLine.set(line,(byLine.get(line)??0)+Number(item.received_quantity??0));}}return byLine;}
function poReceiptStatus(po:ErpDocument,received:Map<number,number>){let any=false;let complete=true;for(const item of po.items){const line=Number(item.line_number??0),ordered=Number(item.quantity??0),qty=received.get(line)??0;if(qty>0)any=true;if(qty<ordered)complete=false;}return !any?"open":complete?"fully_received":"partially_received";}

export async function POST(request:Request){
  const token=tokenOf(request);if(!token)return NextResponse.json({error:"Authentication required"},{status:401});
  const user=await getSupabaseUser(token);if(!user)return NextResponse.json({error:"Invalid session"},{status:401});
  const body=await request.json() as Body;const data=body.data??{};
  try{
    if(body.action==="create_pr"){
      const plant=String(data.plant??"").trim();const lines=normalizedLines(data.items);
      if(!plant||lines.length<2)return NextResponse.json({error:"Plant and at least two requisition items are required for multi-line mode."},{status:400});
      await requireMaster("plant",plant,"Plant",token);
      for(const line of lines){if(!line.material||Number(line.quantity)<=0)return NextResponse.json({error:"Every requisition line requires material and quantity."},{status:400});await requireMaster("material",line.material,"Material",token);}
      const number=docNumber("PRM");await supabaseRest("erp_documents",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({user_id:user.id,document_type:"PR",document_number:number,status:"open",header:{plant,multi_line:true,item_count:lines.length},items:lines.map(line=>({line_number:line.line_number,material:line.material,quantity:line.quantity}))})},token);
      return NextResponse.json({posted:true,documentNumber:number,status:"open",itemCount:lines.length,next:"create_po"});
    }

    if(body.action==="create_po"){
      const sourcePr=String(data.source_pr??"").trim(),vendor=String(data.vendor??"").trim(),pOrg=String(data.purchasing_organization??"").trim(),prices=(data.unit_prices??{}) as Record<string,unknown>;
      const pr=await findDoc(user.id,token,sourcePr,"PR");if(!pr)return NextResponse.json({error:"Choose a purchase requisition that belongs to your account."},{status:400});if(pr.status!=="open")return NextResponse.json({error:`Purchase requisition ${pr.document_number} is ${pr.status} and cannot be converted again.`},{status:400});
      await Promise.all([requireMaster("vendor",vendor,"Vendor",token),requireMaster("purchasing_organization",pOrg,"Purchasing organization",token)]);
      const poItems=[] as Record<string,unknown>[];for(const item of pr.items){const line=Number(item.line_number??0),price=Number(prices[String(line)]??0);if(price<=0)return NextResponse.json({error:`Unit price is required for PO line ${line}.`},{status:400});poItems.push({...item,unit_price:price});}
      const number=docNumber("POM");await supabaseRest("erp_documents",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({user_id:user.id,document_type:"PO",document_number:number,status:"open",header:{source_pr:pr.document_number,vendor,purchasing_organization:pOrg,plant:pr.header.plant,multi_line:true,item_count:poItems.length},items:poItems})},token);await updateDoc(pr,"converted",token);
      return NextResponse.json({posted:true,documentNumber:number,status:"open",sourceDocument:pr.document_number,itemCount:poItems.length,next:"post_gr"});
    }

    if(body.action==="post_gr"){
      const sourcePo=String(data.source_po??"").trim(),postingDate=isoDate(data.posting_date),documentDate=isoDate(data.document_date),movementType=String(data.movement_type??"101");const lines=normalizedLines(data.items);
      if(documentDate>postingDate)return NextResponse.json({error:"Document date cannot be after posting date."},{status:400});if(movementType!=="101")return NextResponse.json({error:"Multi-line goods receipt supports movement type 101 only."},{status:400});
      const po=await findDoc(user.id,token,sourcePo,"PO");if(!po)return NextResponse.json({error:"Choose a purchase order that belongs to your account."},{status:400});if(po.status==="closed")return NextResponse.json({error:"This purchase order is closed."},{status:400});if(lines.length===0)return NextResponse.json({error:"At least one receipt line is required."},{status:400});
      const existing=await receipts(user.id,token,sourcePo);const totals=receiptTotals(existing);const plant=String(po.header.plant??"");const postedItems:Record<string,unknown>[]=[];const balances:Record<string,number>={};
      for(const line of lines){const poLine=po.items.find(item=>Number(item.line_number??0)===Number(line.line_number));if(!poLine)return NextResponse.json({error:`PO line ${line.line_number} does not exist.`},{status:400});const qty=Number(line.received_quantity??0),ordered=Number(poLine.quantity??0),already=totals.get(Number(line.line_number))??0;if(qty<=0)return NextResponse.json({error:`Received quantity is required for PO line ${line.line_number}.`},{status:400});if(already+qty>ordered)return NextResponse.json({error:`Receipt would exceed open quantity for PO line ${line.line_number}.`},{status:400});const material=String(poLine.material??"");const storage=String(line.storage_location??"SL01");const storageRow=await master("storage_location",storage,token);if(!storageRow)throw new Error(`Storage location ${storage} is not an active ERP master-data value.`);const storagePlant=linkedPlant(storageRow);if(storagePlant&&storagePlant!==plant)return NextResponse.json({error:`Storage location ${storage} belongs to plant ${storagePlant}, not ${plant}.`},{status:400});const before=await balance(user.id,token,material,plant,storage),after=before+qty;await setBalance(user.id,token,material,plant,storage,after);balances[`${material}@${storage}`]=after;postedItems.push({line_number:Number(line.line_number),material,received_quantity:qty,storage_location:storage});totals.set(Number(line.line_number),already+qty);}
      const status=poReceiptStatus(po,totals),number=docNumber("GRM");await supabaseRest("erp_documents",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({user_id:user.id,document_type:"GR",document_number:number,status:"posted",header:{source_po:po.document_number,plant,posting_date:postingDate,document_date:documentDate,movement_type:"101",multi_line:true,item_count:postedItems.length,po_receipt_status:status},items:postedItems})},token);await updateDoc(po,status,token);
      return NextResponse.json({posted:true,documentNumber:number,status:"posted",sourceDocument:po.document_number,poStatus:status,itemCount:postedItems.length,inventoryBalances:balances,next:"post_invoice"});
    }

    if(body.action==="post_invoice"){
      const sourcePo=String(data.source_po??"").trim(),supplierInvoiceNumber=String(data.supplier_invoice_number??"").trim(),invoiceValue=Number(data.invoice_value??0),invoiceDate=isoDate(data.invoice_date),postingDate=isoDate(data.posting_date);
      if(invoiceDate>postingDate)return NextResponse.json({error:"Invoice date cannot be after posting date."},{status:400});if(!supplierInvoiceNumber||invoiceValue<=0)return NextResponse.json({error:"Supplier invoice number and invoice value are required."},{status:400});
      const po=await findDoc(user.id,token,sourcePo,"PO");if(!po)return NextResponse.json({error:"Choose a purchase order that belongs to your account."},{status:400});if(po.status==="closed")return NextResponse.json({error:"This purchase order is already closed."},{status:400});const active=await invoices(user.id,token,sourcePo);if(active.some(row=>row.status==="blocked"))return NextResponse.json({error:`Reverse blocked invoice ${active.find(row=>row.status==="blocked")?.document_number} before entering a corrected invoice.`},{status:409});
      const rec=await receipts(user.id,token,sourcePo);if(rec.length===0)return NextResponse.json({error:"Post at least one goods receipt before invoice verification."},{status:400});const totals=receiptTotals(rec);let poValue=0,receivedValue=0,receivedAll=true;const matchItems=[] as Record<string,unknown>[];for(const item of po.items){const line=Number(item.line_number??0),ordered=Number(item.quantity??0),price=Number(item.unit_price??0),received=totals.get(line)??0;poValue+=ordered*price;receivedValue+=received*price;if(received<ordered)receivedAll=false;matchItems.push({line_number:line,material:item.material,ordered_quantity:ordered,received_quantity:received,unit_price:price,received_value:received*price});}
      const variance=Number((invoiceValue-receivedValue).toFixed(2)),matchStatus=Math.abs(variance)<0.01?"matched":"mismatch",status=matchStatus==="matched"?"posted":"blocked",number=docNumber("IVM");await supabaseRest("erp_documents",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({user_id:user.id,document_type:"IV",document_number:number,status,header:{source_po:po.document_number,vendor:po.header.vendor,supplier_invoice_number:supplierInvoiceNumber,invoice_date:invoiceDate,posting_date:postingDate,match_status:matchStatus,po_value:poValue,received_value:receivedValue,invoice_value:invoiceValue,variance,multi_line:true,item_count:po.items.length,block_reason:status==="blocked"?`Invoice variance ${variance>0?"+":""}${variance.toFixed(2)} against received value.`:null},items:matchItems})},token);if(status==="posted"&&receivedAll)await updateDoc(po,"closed",token);
      return NextResponse.json({posted:true,documentNumber:number,status,sourceDocument:po.document_number,matchStatus,poValue,receivedValue,invoiceValue,variance,complete:status==="posted"&&receivedAll,poStatus:status==="posted"&&receivedAll?"closed":po.status});
    }

    if(body.action==="reverse_invoice"){
      const sourceInvoice=String(data.source_invoice??"").trim();const invoice=await findDoc(user.id,token,sourceInvoice,"IV");if(!invoice)return NextResponse.json({error:"Choose an invoice that belongs to your account."},{status:400});if(!["posted","blocked"].includes(invoice.status))return NextResponse.json({error:`Invoice ${invoice.document_number} is ${invoice.status} and cannot be reversed.`},{status:400});const po=await findDoc(user.id,token,String(invoice.header.source_po??""),"PO");if(!po)return NextResponse.json({error:"Source purchase order not found."},{status:400});await updateDoc(invoice,"reversed",token,{...invoice.header,reversal_date:new Date().toISOString().slice(0,10)});const totals=receiptTotals(await receipts(user.id,token,po.document_number));const status=poReceiptStatus(po,totals);if(po.status==="closed")await updateDoc(po,status,token);return NextResponse.json({reversed:true,documentNumber:invoice.document_number,status:"reversed",poStatus:status});
    }

    if(body.action==="reverse_gr"){
      const sourceGr=String(data.source_gr??"").trim();const gr=await findDoc(user.id,token,sourceGr,"GR");if(!gr)return NextResponse.json({error:"Choose a goods receipt that belongs to your account."},{status:400});if(gr.status!=="posted")return NextResponse.json({error:`Goods receipt ${gr.document_number} is ${gr.status} and cannot be reversed.`},{status:400});const po=await findDoc(user.id,token,String(gr.header.source_po??""),"PO");if(!po)return NextResponse.json({error:"Source purchase order not found."},{status:400});const active=await invoices(user.id,token,po.document_number);if(active.length>0)return NextResponse.json({error:`Reverse active invoice ${active[0].document_number} before reversing goods receipt ${gr.document_number}.`},{status:409});const plant=String(gr.header.plant??po.header.plant??"");const balances:Record<string,number>={};for(const item of gr.items){const material=String(item.material??""),storage=String(item.storage_location??"SL01"),qty=Number(item.received_quantity??0),before=await balance(user.id,token,material,plant,storage);if(before<qty)return NextResponse.json({error:`Inventory balance is lower than receipt quantity for line ${item.line_number}.`},{status:409});const after=before-qty;await setBalance(user.id,token,material,plant,storage,after);balances[`${material}@${storage}`]=after;}await updateDoc(gr,"reversed",token,{...gr.header,reversal_date:new Date().toISOString().slice(0,10),reversal_movement_type:"102"});const totals=receiptTotals((await receipts(user.id,token,po.document_number)).filter(row=>row.document_number!==gr.document_number));const status=poReceiptStatus(po,totals);await updateDoc(po,status,token);return NextResponse.json({reversed:true,documentNumber:gr.document_number,status:"reversed",poStatus:status,inventoryBalances:balances});
    }

    return NextResponse.json({error:"Unsupported multi-line procurement action"},{status:400});
  }catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Multi-line procurement validation failed."},{status:400});}
}
