import { NextResponse } from "next/server";
import { getSupabaseUser, supabaseRest } from "../../../lib/supabase";

type Assessment={id:string;course_id:string;slug:string;title:string;description:string;duration_minutes:number;passing_score:number;max_ai_help:number;blueprint:{expected?:Record<string,unknown>;sections?:Array<{key:string;weight:number}>}};
type Attempt={id:string;assessment_id:string;user_id:string;started_at:string;expires_at:string;submitted_at:string|null;status:string;submitted_state:Record<string,unknown>;score:number|null;ai_help_count:number;independence_score:number|null;feedback:Record<string,unknown>};
type Enrollment={status:string;progress_percent:number};
type Competency={skill_key:string;level:string};

function tokenFrom(request:Request){const a=request.headers.get("authorization");return a?.startsWith("Bearer ")?a.slice(7):undefined;}
function normalize(v:unknown):unknown{if(typeof v==="string")return v.trim().toLowerCase();if(Array.isArray(v))return v.map(normalize);if(v&&typeof v==="object")return Object.fromEntries(Object.entries(v as Record<string,unknown>).map(([k,x])=>[k,normalize(x)]));return v;}
function atLeastApplied(level:string|undefined){return level==="applied"||level==="competent";}

async function context(request:Request){
  const token=tokenFrom(request);if(!token)return null;
  const user=await getSupabaseUser(token);if(!user)return null;
  const assessments=await supabaseRest<Assessment[]>("job_readiness_assessments?slug=eq.sap-mm-level-1-job-readiness&is_published=eq.true&select=id,course_id,slug,title,description,duration_minutes,passing_score,max_ai_help,blueprint&limit=1",{},token);const assessment=assessments[0];if(!assessment)return null;
  const courses=await supabaseRest<{id:string}[]>("courses?slug=eq.sap-mm-level-1&select=id&limit=1",{},token);const l1=courses[0];
  if(!l1||assessment.course_id!==l1.id)return null;
  const enrollments=await supabaseRest<Enrollment[]>(`enrollments?user_id=eq.${user.id}&course_id=eq.${l1.id}&select=status,progress_percent&limit=1`,{},token);
  const competencies=await supabaseRest<Competency[]>(`competencies?user_id=eq.${user.id}&course_id=eq.${l1.id}&skill_key=in.(independent_sap_mm_work,incident_investigation)&select=skill_key,level`,{},token);
  const bySkill=new Map(competencies.map(c=>[c.skill_key,c.level]));
  const courseComplete=enrollments[0]?.status==="completed"&&Number(enrollments[0]?.progress_percent)>=100;
  const eligible=courseComplete&&atLeastApplied(bySkill.get("independent_sap_mm_work"))&&atLeastApplied(bySkill.get("incident_investigation"));
  return {token,user,assessment,eligible,courseComplete,competencies:Object.fromEntries(bySkill)};
}

export async function GET(request:Request){const ctx=await context(request);if(!ctx)return NextResponse.json({error:"Authentication required or assessment unavailable"},{status:401});if(!ctx.eligible)return NextResponse.json({eligible:false,error:"Complete SAP MM Level 1, pass a Work Lab task, and resolve an Incident Lab case before attempting job readiness.",requirements:{courseComplete:ctx.courseComplete,competencies:ctx.competencies}},{status:403});const attempts=await supabaseRest<Attempt[]>(`job_readiness_attempts?user_id=eq.${ctx.user.id}&assessment_id=eq.${ctx.assessment.id}&select=id,assessment_id,user_id,started_at,expires_at,submitted_at,status,submitted_state,score,ai_help_count,independence_score,feedback&order=started_at.desc`,{},ctx.token);const active=attempts.find(a=>a.status==="in_progress"&&new Date(a.expires_at).getTime()>Date.now())??null;return NextResponse.json({eligible:true,assessment:{id:ctx.assessment.id,title:ctx.assessment.title,description:ctx.assessment.description,durationMinutes:ctx.assessment.duration_minutes,passingScore:ctx.assessment.passing_score,maxAiHelp:ctx.assessment.max_ai_help,fields:Object.keys(ctx.assessment.blueprint.expected??{})},activeAttempt:active,attempts});}

export async function POST(request:Request){const ctx=await context(request);if(!ctx)return NextResponse.json({error:"Authentication required or assessment unavailable"},{status:401});if(!ctx.eligible)return NextResponse.json({error:"Complete SAP MM Level 1, pass Work Lab, and resolve Incident Lab first."},{status:403});const body=await request.json() as {action?:"start"|"submit"|"ai_help";attemptId?:string;answers?:Record<string,unknown>};
 if(body.action==="start"){const existing=await supabaseRest<Attempt[]>(`job_readiness_attempts?user_id=eq.${ctx.user.id}&assessment_id=eq.${ctx.assessment.id}&status=eq.in_progress&select=id,expires_at&order=started_at.desc&limit=1`,{},ctx.token);if(existing[0]&&new Date(existing[0].expires_at).getTime()>Date.now())return NextResponse.json({attemptId:existing[0].id,expiresAt:existing[0].expires_at,resumed:true});const expiresAt=new Date(Date.now()+ctx.assessment.duration_minutes*60_000).toISOString();const created=await supabaseRest<Attempt[]>("job_readiness_attempts",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({assessment_id:ctx.assessment.id,user_id:ctx.user.id,expires_at:expiresAt,status:"in_progress"})},ctx.token);return NextResponse.json({attemptId:created[0]?.id,expiresAt,resumed:false});}
 if(!body.attemptId)return NextResponse.json({error:"attemptId is required"},{status:400});const rows=await supabaseRest<Attempt[]>(`job_readiness_attempts?id=eq.${body.attemptId}&user_id=eq.${ctx.user.id}&assessment_id=eq.${ctx.assessment.id}&select=id,assessment_id,user_id,started_at,expires_at,submitted_at,status,submitted_state,score,ai_help_count,independence_score,feedback&limit=1`,{},ctx.token);const attempt=rows[0];if(!attempt)return NextResponse.json({error:"Attempt not found"},{status:404});if(attempt.status!=="in_progress")return NextResponse.json({error:"Attempt already closed"},{status:400});if(new Date(attempt.expires_at).getTime()<=Date.now()){await supabaseRest(`job_readiness_attempts?id=eq.${attempt.id}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({status:"expired"})},ctx.token);return NextResponse.json({error:"Assessment time expired"},{status:410});}
 if(body.action==="ai_help"){if(attempt.ai_help_count>=ctx.assessment.max_ai_help)return NextResponse.json({error:"AI assistance limit reached for this assessment."},{status:403});const next=attempt.ai_help_count+1;await supabaseRest(`job_readiness_attempts?id=eq.${attempt.id}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({ai_help_count:next})},ctx.token);return NextResponse.json({aiHelpCount:next,remaining:ctx.assessment.max_ai_help-next,hint:"Use the document flow: identify what already exists, calculate open quantities from cumulative receipts, and validate invoice value only against supported received value."});}
 if(body.action==="submit"){const expected=ctx.assessment.blueprint.expected??{};const answers=body.answers??{};const keys=Object.keys(expected);const normalizedExpected=normalize(expected) as Record<string,unknown>;const normalizedAnswers=normalize(answers) as Record<string,unknown>;const details=keys.map(k=>({key:k,correct:JSON.stringify(normalizedExpected[k])===JSON.stringify(normalizedAnswers[k])}));const correct=details.filter(x=>x.correct).length;const score=Math.round((correct/Math.max(keys.length,1))*100);const independenceScore=Math.max(0,100-attempt.ai_help_count*25);const passed=score>=ctx.assessment.passing_score&&attempt.ai_help_count<=ctx.assessment.max_ai_help;const status=passed?"passed":"failed";const feedback={correctFields:details.filter(x=>x.correct).map(x=>x.key),reviewFields:details.filter(x=>!x.correct).map(x=>x.key),passingScore:ctx.assessment.passing_score};await supabaseRest(`job_readiness_attempts?id=eq.${attempt.id}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({submitted_state:answers,score,independence_score:independenceScore,status,submitted_at:new Date().toISOString(),feedback})},ctx.token);await supabaseRest("rpc/record_competency_evidence_from_source",{method:"POST",body:JSON.stringify({p_source_type:"job_readiness",p_source_id:attempt.id,p_skill_key:"sap_mm_job_readiness"})},ctx.token);await supabaseRest("rpc/record_competency_evidence_from_source",{method:"POST",body:JSON.stringify({p_source_type:"job_readiness",p_source_id:attempt.id,p_skill_key:"independent_sap_mm_work"})},ctx.token);return NextResponse.json({passed,score,independenceScore,status,feedback});}
 return NextResponse.json({error:"Unsupported action"},{status:400});
}
