import { NextResponse } from "next/server";
import { getSupabaseUser, supabaseRest } from "../../../lib/supabase";

type Enrollment={status:string;progress_percent:number};
type Task={id:string;title:string;description:string;task_type:string;difficulty:string};
type WorkAttempt={task_id:string;result:string;completed_at:string|null};
type Incident={id:string;incident_type:string;title:string;description:string;priority:string;source_document_number:string|null;status:string;created_at:string};
type InboxEvent={document_number:string;header:Record<string,unknown>};

function tokenFrom(request:Request){const auth=request.headers.get("authorization");return auth?.startsWith("Bearer ")?auth.slice(7):undefined;}
function priorityWeight(p:string){return p==="high"?3:p==="normal"?2:1;}
function dueIso(hours:number){return new Date(Date.now()+hours*60*60*1000).toISOString();}
async function context(request:Request){const token=tokenFrom(request);if(!token)return null;const user=await getSupabaseUser(token);if(!user)return null;const courses=await supabaseRest<{id:string}[]>("courses?slug=eq.sap-mm-level-1&select=id&limit=1",{},token);const course=courses[0];if(!course)return null;const enrollments=await supabaseRest<Enrollment[]>(`enrollments?user_id=eq.${user.id}&course_id=eq.${course.id}&select=status,progress_percent&limit=1`,{},token);const unlocked=enrollments[0]?.status==="completed"&&Number(enrollments[0]?.progress_percent)>=100;return {token,user,course,unlocked};}
export async function GET(request:Request){const ctx=await context(request);if(!ctx)return NextResponse.json({error:"Authentication required"},{status:401});if(!ctx.unlocked)return NextResponse.json({error:"Workplace inbox locked"},{status:403});const [tasks,attempts,incidents,events]=await Promise.all([
 supabaseRest<Task[]>(`work_lab_tasks?course_id=eq.${ctx.course.id}&is_published=eq.true&select=id,title,description,task_type,difficulty&order=created_at.asc`,{},ctx.token),
 supabaseRest<WorkAttempt[]>(`work_lab_attempts?user_id=eq.${ctx.user.id}&select=task_id,result,completed_at`,{},ctx.token),
 supabaseRest<Incident[]>(`work_lab_incidents?user_id=eq.${ctx.user.id}&select=id,incident_type,title,description,priority,source_document_number,status,created_at&order=created_at.desc`,{},ctx.token),
 supabaseRest<InboxEvent[]>(`erp_documents?user_id=eq.${ctx.user.id}&document_type=eq.WORK_INBOX_EVENT&select=document_number,header`,{},ctx.token)
]);const acknowledged=new Set(events.filter(e=>String(e.header.event_type)==="acknowledged").map(e=>String(e.header.item_key)));
 const taskItems=tasks.map((t,i)=>{const passed=attempts.some(a=>a.task_id===t.id&&a.result==="pass");return {key:`task:${t.id}`,kind:"work_ticket",title:t.title,description:t.description,priority:t.difficulty==="hard"?"high":t.difficulty==="medium"?"normal":"low",dueAt:dueIso((i+1)*8),status:passed?"completed":acknowledged.has(`task:${t.id}`)?"acknowledged":"open",actionUrl:"/work-lab",linkedDocument:null,sourceId:t.id};});
 const incidentItems=incidents.map((x,i)=>({key:`incident:${x.id}`,kind:"exception",title:x.title,description:x.description,priority:x.priority||"normal",dueAt:dueIso((i+1)*4),status:x.status==="resolved"?"completed":acknowledged.has(`incident:${x.id}`)?"acknowledged":"open",actionUrl:"/work-lab/incidents",linkedDocument:x.source_document_number,sourceId:x.id}));
 const items=[...incidentItems,...taskItems].sort((a,b)=>{const done=(x:string)=>x==="completed"?1:0;return done(a.status)-done(b.status)||priorityWeight(b.priority)-priorityWeight(a.priority)||a.dueAt.localeCompare(b.dueAt);});return NextResponse.json({items,summary:{open:items.filter(x=>x.status==="open").length,acknowledged:items.filter(x=>x.status==="acknowledged").length,completed:items.filter(x=>x.status==="completed").length,exceptions:items.filter(x=>x.kind==="exception"&&x.status!=="completed").length}});}
export async function POST(request:Request){const ctx=await context(request);if(!ctx)return NextResponse.json({error:"Authentication required"},{status:401});if(!ctx.unlocked)return NextResponse.json({error:"Workplace inbox locked"},{status:403});const body=await request.json() as {itemKey?:string};const itemKey=String(body.itemKey??"").trim();if(!/^(task|incident):/.test(itemKey))return NextResponse.json({error:"Valid itemKey is required"},{status:400});const doc=`INBOX-${itemKey.replace(/[^a-zA-Z0-9]/g,"").slice(-20)}`;const existing=await supabaseRest<Array<{id:string}>>(`erp_documents?user_id=eq.${ctx.user.id}&document_type=eq.WORK_INBOX_EVENT&document_number=eq.${encodeURIComponent(doc)}&select=id&limit=1`,{},ctx.token);if(existing.length)return NextResponse.json({acknowledged:true,duplicate:true,documentNumber:doc});await supabaseRest("erp_documents",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({user_id:ctx.user.id,document_type:"WORK_INBOX_EVENT",document_number:doc,status:"posted",header:{event_type:"acknowledged",item_key:itemKey,acknowledged_at:new Date().toISOString(),training_phase:"6D"},items:[]})},ctx.token);return NextResponse.json({acknowledged:true,duplicate:false,documentNumber:doc});}
