"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { authenticatedFetch } from "../../lib/auth-client";

type Doc={document_number:string;document_type:string;status:string;header:Record<string,unknown>;items:Array<Record<string,unknown>>};
type Runtime={documents:Doc[]};

export default function AccountingImpactPage(){
  const [runtime,setRuntime]=useState<Runtime|null>(null);const [busy,setBusy]=useState("");const [message,setMessage]=useState("");
  async function load(){const r=await authenticatedFetch("/api/erp-runtime");if(r?.ok)setRuntime(await r.json());}
  useEffect(()=>{void load();},[]);
  const docs=runtime?.documents??[];const sources=docs.filter(d=>(d.document_type==="GR"&&d.status==="posted")||(d.document_type==="IV"&&d.status==="posted"));const fis=docs.filter(d=>d.document_type==="FI");
  const accounted=useMemo(()=>new Set(fis.filter(d=>d.status!=="reversed").map(d=>String(d.header.source_document??""))),[fis]);
  async function postSource(number:string){setBusy(number);setMessage("");try{const r=await authenticatedFetch("/api/accounting-impact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"post_source",data:{source_document:number}})});const p=r?await r.json():{};setMessage(r?.ok?`Success · FI ${p.documentNumber} · debits ${Number(p.debit??0).toFixed(2)} = credits ${Number(p.credit??0).toFixed(2)}.`:`Error · ${p.error??"Unable to create FI document."}`);if(r?.ok)await load();}finally{setBusy("");}}
  async function reverseFi(number:string){setBusy(number);setMessage("");try{const r=await authenticatedFetch("/api/accounting-impact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"reverse_fi",data:{fi_document:number}})});const p=r?await r.json():{};setMessage(r?.ok?`Success · reversed ${number} with ${p.reversalDocument}.`:`Error · ${p.error??"Unable to reverse FI document."}`);if(r?.ok)await load();}finally{setBusy("");}}
  return <main style={{minHeight:"100vh",background:"#f6f8fb",padding:"20px",color:"#172033"}}>
    <div style={{maxWidth:1100,margin:"0 auto"}}><header style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",marginBottom:18}}><Link href="/procurement-flow/multiline">← Procurement</Link><strong>ERP Edu · MM → FI Accounting Impact</strong><Link href="/dashboard">Dashboard</Link></header>
      <section style={{background:"white",border:"1px solid #e4e7ec",borderRadius:16,padding:22,marginBottom:18}}><span style={{fontSize:12,fontWeight:700,color:"#667085"}}>PHASE 4D · WORKPLACE REALISM</span><h1 style={{margin:"8px 0"}}>See what procurement posts into Finance.</h1><p style={{margin:0,color:"#667085"}}>Generate the accounting document behind a goods receipt or posted invoice, inspect debit/credit lines, and practice reversal without losing the audit trail.</p></section>
      <section style={{background:"white",border:"1px solid #e4e7ec",borderRadius:16,padding:18,marginBottom:18}}><h2>Source MM documents</h2><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:700}}><thead><tr><th align="left">Type</th><th align="left">Document</th><th align="left">Status</th><th align="left">Accounting</th><th></th></tr></thead><tbody>{sources.map(d=><tr key={d.document_number}><td style={{padding:"10px 6px",borderTop:"1px solid #eee"}}>{d.document_type}</td><td style={{padding:"10px 6px",borderTop:"1px solid #eee"}}>{d.document_number}</td><td style={{padding:"10px 6px",borderTop:"1px solid #eee"}}>{d.status}</td><td style={{padding:"10px 6px",borderTop:"1px solid #eee"}}>{accounted.has(d.document_number)?"Posted":"Pending"}</td><td style={{padding:"10px 6px",borderTop:"1px solid #eee"}}><button style={{minHeight:44,padding:"0 14px"}} disabled={busy===d.document_number} onClick={()=>postSource(d.document_number)}>{accounted.has(d.document_number)?"View / reuse FI":"Create FI document"}</button></td></tr>)}</tbody></table></div>{sources.length===0&&<p>No posted GR or invoice documents are available yet.</p>}</section>
      <section style={{background:"white",border:"1px solid #e4e7ec",borderRadius:16,padding:18}}><h2>FI journal</h2>{fis.map(fi=>{const debit=Number(fi.header.total_debit??0),credit=Number(fi.header.total_credit??0);return <article key={fi.document_number} style={{border:"1px solid #e4e7ec",borderRadius:12,padding:14,marginBottom:12}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><strong>{fi.document_number}</strong> · {fi.status}<div style={{fontSize:13,color:"#667085"}}>Source {String(fi.header.source_document??"")} · {String(fi.header.currency??"INR")}</div></div><div><strong>{debit.toFixed(2)} Dr = {credit.toFixed(2)} Cr</strong>{fi.status==="posted"&&<button style={{marginLeft:12,minHeight:40}} disabled={busy===fi.document_number} onClick={()=>reverseFi(fi.document_number)}>Reverse</button>}</div></div><div style={{overflowX:"auto",marginTop:10}}><table style={{width:"100%",minWidth:620,borderCollapse:"collapse"}}><thead><tr><th align="left">Account</th><th align="left">Text</th><th align="right">Debit</th><th align="right">Credit</th></tr></thead><tbody>{fi.items.map((x,i)=><tr key={i}><td>{String(x.account??"")} · {String(x.account_name??"")}</td><td>{String(x.text??"")}</td><td align="right">{Number(x.debit??0).toFixed(2)}</td><td align="right">{Number(x.credit??0).toFixed(2)}</td></tr>)}</tbody></table></div></article>})}{fis.length===0&&<p>No FI documents posted yet.</p>}</section>
      {message&&<div role={message.startsWith("Error")?"alert":"status"} style={{maxWidth:1100,margin:"12px auto",padding:14,borderRadius:10,background:message.startsWith("Error")?"#fef3f2":"#ecfdf3"}}>{message}</div>}
    </div>
  </main>;
}
